### PR TITLE
Remove key_algorithm from tls_cert_request

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Remove `key_algorithm` from `tls_cert_request`
* Remove `ca_key_algorithm` from `tls_locally_signed_cert`

## why
* Deprecated

## references
* Closes https://github.com/cloudposse/terraform-aws-ssm-tls-self-signed-cert/issues/13
* https://registry.terraform.io/providers/hashicorp/tls/latest/docs
* https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/cert_request#key_algorithm

### CODE REVIEW

**Review by korenyoni — APPROVED** [review]
LGTM

**Review by Benbentwo — COMMENTED** [review]
LGTM, thanks for updating the versions

**Review by Nuru — APPROVED** [review]

**Pull request merged**
